### ISSUE TITLE
WrongType error on checkout_workflow_policy, type unicode

### ISSUE THREAD

**Issue by MrTango** [plone/plone.app.upgrade#142]
When I do an upgrade from 4.3.16 to 5.0.8 I get the following error:

```
2017-10-24 09:14:07 ERROR plone.app.upgrade Upgrade aborted. Error:
Traceback (most recent call last):
  File "/usr/local/plone-5.0/buildout-cache/eggs/Products.CMFPlone-5.0.8-py2.7.egg/Products/CMFPlone/MigrationTool.py", line 268, in upgrade
    step['step'].doStep(setup)
  File "/usr/local/plone-5.0/buildout-cache/eggs/Products.GenericSetup-1.8.8-py2.7.egg/Products/GenericSetup/upgrade.py", line 166, in doStep
    self.handler(tool)
  File "/usr/local/plone-5.0/buildout-cache/eggs/plone.app.upgrade-2.0.8-py2.7.egg/plone/app/upgrade/v50/betas.py", line 573, in to50rc3
    settings.checkout_workflow_policy = str(value)
  File "/usr/local/plone-5.0/buildout-cache/eggs/plone.registry-1.0.5-py2.7.egg/plone/registry/recordsproxy.py", line 49, in __setattr__
    self.__registry__[full_name] = value
  File "/usr/local/plone-5.0/buildout-cache/eggs/plone.registry-1.0.5-py2.7.egg/plone/registry/registry.py", line 47, in __setitem__
    self.records[name].value = value
  File "/usr/local/plone-5.0/buildout-cache/eggs/plone.registry-1.0.5-py2.7.egg/plone/registry/record.py", line 82, in _set_value
    field.validate(value)
  File "/usr/local/plone-5.0/buildout-cache/eggs/zope.schema-4.4.2-py2.7.egg/zope/schema/_bootstrapfields.py", line 183, in validate
    self._validate(value)
  File "/usr/local/plone-5.0/buildout-cache/eggs/zope.schema-4.4.2-py2.7.egg/zope/schema/_bootstrapfields.py", line 310, in _validate
    super(MinMaxLen, self)._validate(value)
  File "/usr/local/plone-5.0/buildout-cache/eggs/zope.schema-4.4.2-py2.7.egg/zope/schema/_bootstrapfields.py", line 210, in _validate
    raise WrongType(value, self._type, self.__name__)
WrongType: ('checkout_workflow_policy', <type 'unicode'>, 'value')
```

**Comment by MrTango** [comment]
I think there is something from in the mirgration of the properties to the registry.

A work around is: delete checkout_workflow_policy in ZMI > portal_properties/site_properties
But it should be fixed in the upgrade.

**Comment by mauritsvanrees** [comment]
Already fixed in https://github.com/plone/plone.app.upgrade/pull/140, but not yet released.
