### ISSUE TITLE
Error removing resource registry tools in upgrade

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.upgrade#197]
I tried an upgrade from Plone 5.0.10 to latest 5.2 coredev. The upgrade broke:

```
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/5.2/src/Products.CMFPlone/Products/CMFPlone/MigrationTool.py", line 291, in upgrade
    step['step'].doStep(setup)
  File "/Users/maurits/shared-eggs/cp27m/Products.GenericSetup-2.0b5-py2.7.egg/Products/GenericSetup/upgrade.py", line 168, in doStep
    self.handler(tool)
  File "/Users/maurits/community/plone-coredev/5.2/src/plone.app.upgrade/plone/app/upgrade/v52/betas.py", line 102, in to52beta1
    remove_legacy_resource_registries(context)
  File "/Users/maurits/community/plone-coredev/5.2/src/plone.app.upgrade/plone/app/upgrade/v52/betas.py", line 48, in remove_legacy_resource_registries
    portal.manage_delObjects(tools)
  File "/Users/maurits/community/plone-coredev/5.2/src/Products.CMFPlone/Products/CMFPlone/Portal.py", line 126, in manage_delObjects
    "Do not have permissions to remove this object")
Unauthorized: Do not have permissions to remove this object
```

Any idea?
cc @ksuess

**Comment by mauritsvanrees** [comment]
Ah, I see. The code calls `portal.manage_delObjects` and this does a permission check. For some reason we don't have permission to delete the objects.  This may depend on how we get the portal object, and maybe we lose the `REQUEST` object or something. I don't know.
But we should simply call `portal._delObject` instead and our problems will be gone.

I created PR #198 with a fix.
