### ISSUE TITLE
Upgrade to 6.0.0a1 fails

### ISSUE THREAD

**Issue by Rudd-O** [plone/plone.app.upgrade#263]
Here is the upgrade report:

```
Upgrade report

Dry run selected.
Starting the migration from version: 5210
Ran upgrade step: Migrate site logo from native string to bytes again
Made portal_setup logs only available for Manager and Owner.
Made portal_setup snapshots only available for Manager and Owner.
Ran upgrade step: Make portal_setup logs accessible only to Manager/Owner.
Ran upgrade step: Miscellaneous
Ran upgrade step: Miscellaneous
Types tool imported.
Upgrade aborted. Error:
Traceback (most recent call last):
  File "/home/user/optplone/buildout-cache/eggs/Products.CMFPlone-6.0.0a1-py3.8.egg/Products/CMFPlone/MigrationTool.py", line 302, in upgrade
    step['step'].doStep(setup)
  File "/home/user/optplone/buildout-cache/eggs/Products.GenericSetup-2.1.4-py3.8.egg/Products/GenericSetup/upgrade.py", line 168, in doStep
    self.handler(tool)
  File "/home/user/optplone/buildout-cache/eggs/plone.app.upgrade-2.0.41-py3.8.egg/plone/app/upgrade/v60/alphas.py", line 66, in change_plone_site_fti
    loadMigrationProfile(context, "profile-plone.app.upgrade.v60:to_dx_site_root")
  File "/home/user/optplone/buildout-cache/eggs/plone.app.upgrade-2.0.41-py3.8.egg/plone/app/upgrade/utils.py", line 203, in loadMigrationProfile
    context.runAllImportStepsFromProfile(profile, purge_old=False)
  File "/home/user/optplone/buildout-cache/eggs/Products.GenericSetup-2.1.4-py3.8.egg/Products/GenericSetup/tool.py", line 399, in runAllImportStepsFromProfile
    result = self._runImportStepsFromContext(
  File "/home/user/optplone/buildout-cache/eggs/Products.GenericSetup-2.1.4-py3.8.egg/Products/GenericSetup/tool.py", line 1487, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
  File "/home/user/optplone/buildout-cache/eggs/Products.GenericSetup-2.1.4-py3.8.egg/Products/GenericSetup/tool.py", line 1299, in _doRunImportStep
    return handler(context)
  File "/home/user/optplone/buildout-cache/eggs/Products.CMFCore-2.5.4-py3.8.egg/Products/CMFCore/exportimport/typeinfo.py", line 222, in importTypesTool
    importObjects(tool, '', context)
  File "/home/user/optplone/buildout-cache/eggs/Products.GenericSetup-2.1.4-py3.8.egg/Products/GenericSetup/utils.py", line 960, in importObjects
    importObjects(sub, path + '/', context)
  File "/home/user/optplone/buildout-cache/eggs/Products.GenericSetup-2.1.4-py3.8.egg/Products/GenericSetup/utils.py", line 956, in importObjects
    importer.body = body
  File "/home/user/optplone/buildout-cache/eggs/Products.GenericSetup-2.1.4-py3.8.egg/Products/GenericSetup/utils.py", line 557, in _importBody
    self._importNode(dom.documentElement)
  File "/home/user/optplone/buildout-cache/eggs/Products.CMFCore-2.5.4-py3.8.egg/Products/CMFCore/exportimport/typeinfo.py", line 61, in _importNode
    self._initProperties(node)
  File "/home/user/optplone/buildout-cache/eggs/Products.GenericSetup-2.1.4-py3.8.egg/Products/GenericSetup/utils.py", line 865, in _initProperties
    obj._updateProperty(prop_id, prop_value)
  File "/home/user/optplone/buildout-cache/eggs/plone.dexterity-2.10.4-py3.8.egg/plone/dexterity/fti.py", line 300, in _updateProperty
    modified(self, DexterityFTIModificationDescription(id, oldValue))
  File "/home/user/optplone/buildout-cache/eggs/zope.lifecycleevent-4.3-py3.8.egg/zope/lifecycleevent/__init__.py", line 78, in modified
    notify(ObjectModifiedEvent(object, *descriptions))
  File "/home/user/optplone/buildout-cache/eggs/zope.event-4.5.0-py3.8.egg/zope/event/__init__.py", line 32, in notify
    subscriber(event)
  File "/home/user/optplone/buildout-cache/eggs/zope.component-4.6.2-py3.8.egg/zope/component/event.py", line 27, in dispatch
    component_subscribers(event, None)
  File "/home/user/optplone/buildout-cache/eggs/zope.component-4.6.2-py3.8.egg/zope/component/_api.py", line 134, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/user/optplone/buildout-cache/eggs/zope.interface-5.4.0-py3.8-linux-x86_64.egg/zope/interface/registry.py", line 448, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/user/optplone/buildout-cache/eggs/zope.interface-5.4.0-py3.8-linux-x86_64.egg/zope/interface/adapter.py", line 899, in subscribers
    subscription(*objects)
  File "/home/user/optplone/buildout-cache/eggs/zope.component-4.6.2-py3.8.egg/zope/component/event.py", line 36, in objectEventNotify
    component_subscribers((event.object, event), None)
  File "/home/user/optplone/buildout-cache/eggs/zope.component-4.6.2-py3.8.egg/zope/component/_api.py", line 134, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/user/optplone/buildout-cache/eggs/zope.interface-5.4.0-py3.8-linux-x86_64.egg/zope/interface/registry.py", line 448, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/user/optplone/buildout-cache/eggs/zope.interface-5.4.0-py3.8-linux-x86_64.egg/zope/interface/adapter.py", line 899, in subscribers
    subscription(*objects)
  File "/home/user/optplone/buildout-cache/eggs/plone.dexterity-2.10.4-py3.8.egg/plone/dexterity/fti.py", line 531, in ftiModified
    unregister_factory(old_factory, site_manager)
  File "/home/user/optplone/buildout-cache/eggs/plone.dexterity-2.10.4-py3.8.egg/plone/dexterity/fti.py", line 450, in unregister_factory
    utilities = list(site_manager.registeredUtilities())
  File "/home/user/optplone/buildout-cache/eggs/five.localsitemanager-3.2.2-py3.8.egg/five/localsitemanager/registry.py", line 239, in registeredUtilities
    reg.component = _wrap(reg.component, self)
  File "/home/user/optplone/buildout-cache/eggs/five.localsitemanager-3.2.2-py3.8.egg/five/localsitemanager/registry.py", line 142, in _wrap
    if registry.__bases__ and IAcquirer.providedBy(comp):
  File "/home/user/optplone/buildout-cache/eggs/ZODB-5.6.0-py3.8.egg/ZODB/Connection.py", line 795, in setstate
    self._reader.setGhostState(obj, p)
  File "/home/user/optplone/buildout-cache/eggs/ZODB-5.6.0-py3.8.egg/ZODB/serialize.py", line 633, in setGhostState
    state = self.getState(pickle)
  File "/home/user/optplone/buildout-cache/eggs/ZODB-5.6.0-py3.8.egg/ZODB/serialize.py", line 626, in getState
    return unpickler.load()
  File "/home/user/optplone/buildout-cache/eggs/zope.interface-5.4.0-py3.8-linux-x86_64.egg/zope/interface/declarations.py", line 891, in Provides
    spec = ProvidesClass(*interfaces)
  File "/home/user/optplone/buildout-cache/eggs/zope.interface-5.4.0-py3.8-linux-x86_64.egg/zope/interface/declarations.py", line 822, in __init__
    Declaration.__init__(self, *self._add_interfaces_to_cls(interfaces, cls))
  File "/home/user/optplone/buildout-cache/eggs/zope.interface-5.4.0-py3.8-linux-x86_64.egg/zope/interface/declarations.py", line 87, in __init__
    Specification.__init__(self, _normalizeargs(bases))
  File "/home/user/optplone/buildout-cache/eggs/zope.interface-5.4.0-py3.8-linux-x86_64.egg/zope/interface/declarations.py", line 1307, in _normalizeargs
    _normalizeargs(v, output)
  File "/home/user/optplone/buildout-cache/eggs/zope.interface-5.4.0-py3.8-linux-x86_64.egg/zope/interface/declarations.py", line 1306, in _normalizeargs
    for v in sequence:
TypeError: 'type' object is not iterable
End of upgrade path, main migration has finished.
The upgrade path did NOT reach current version.
Migration has failed
Dry run selected, transaction aborted
```

**Comment by Rudd-O** [comment]
I am so excited about the talks in Ploneconf this year.  Looking forward to the containers I can run Plone frontend and ZEO from, as well as deploy my policy and theme packages into.
