### ISSUE TITLE
TypeError: 'NoneType' object is not iterable in fix_unicode_properties

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.upgrade#270]
Migrating a site from Plone 5.2 to 6.0.0a3:

```
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp39/Products.CMFPlone-6.0.0a3-py3.9.egg/Products/CMFPlone/MigrationTool.py", line 302, in upgrade
    step['step'].doStep(setup)
  File "/Users/maurits/shared-eggs/cp39/Products.GenericSetup-2.1.5-py3.9.egg/Products/GenericSetup/upgrade.py", line 169, in doStep
    self.handler(tool)
  File "/Users/maurits/shared-eggs/cp39/plone.app.upgrade-3.0.0a3-py3.9.egg/plone/app/upgrade/v60/alphas.py", line 266, in fix_unicode_properties
    portal.ZopeFindAndApply(portal, search_sub=1, apply_func=fix_properties)
  File "/Users/maurits/shared-eggs/cp39/Zope-5.4-py3.9.egg/OFS/FindSupport.py", line 171, in ZopeFindAndApply
    self.ZopeFindAndApply(ob, obj_ids, obj_metatypes,
  File "/Users/maurits/shared-eggs/cp39/Zope-5.4-py3.9.egg/OFS/FindSupport.py", line 165, in ZopeFindAndApply
    apply_func(ob, (apply_path + '/' + p))
  File "/Users/maurits/shared-eggs/cp39/Zope-5.4-py3.9.egg/ZPublisher/utils.py", line 149, in fix_properties
    prop_map = obj.propertyMap()
  File "/Users/maurits/shared-eggs/cp39/Zope-5.4-py3.9.egg/OFS/PropertyManager.py", line 252, in propertyMap
    return tuple(dict.copy() for dict in self._propertyMap())
TypeError: 'NoneType' object is not iterable
```

The object where it fails, is `portal_skins/CMFEditions`. This skin layer no longer exists, and will be removed further on in the upgrade. 

In `fix_unicode_properties` we do a `try/except AttributeError` around the call to `obj.propertyMap()`. There may be more things that can go wrong in corner cases like this, so a try/except for `AttributeError/TypeError/ValueError/KeyError` may be best.
Note that the `fix_unicode_properties` function is in Zope (I created it), but we have an own copy, which I added for the time that a Zope 5.4 release was not yet made. We should fix it in both places, and use our own version for the moment.

**Comment by mauritsvanrees** [comment]
Also, I get this error when the code gets to the `portal_url` tool:

```
...  File ".../plone/app/upgrade/v60/alphas.py", line 236, in _fix_properties
    obj._updateProperty(prop_id, new)
AttributeError: _updateProperty
```

I will catch this error as well.
